name: checkin
description: KMU check in AP

version: 1.0.1+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  qrscan: ^0.2.17
  firebase_database: ^3.0.0
  provider_architecture: ^1.1.1+1
  firebase_messaging: ^6.0.16
  get_it: ^4.0.2
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  provider: ^4.0.1
  json_table: ^1.4.0
  intl: ^0.16.1
  font_awesome_flutter: ^8.8.1
  shared_preferences: ^0.5.10
  json_serializable: ^3.3.0
  qr_code_scanner: ^0.0.13
  audioplayers: ^0.16.0
  flutter_launcher_icons: ^0.7.4
  flutter_automation: ^1.4.0
  url_launcher: ^5.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/fonts/
  fonts:
    # - family: Raleway
    #   fonts:
    #     - asset: fonts/Raleway-Regular.ttf
    #     - asset: fonts/Raleway-Italic.ttf
    #       style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
flutter_icons:
  image_path: "assets/images/applogo.JPG"
  android: true
  ios: true
